'use client';
import { useEffect, useState } from 'react';

// เมนูแปลภาษา — dropdown ธงชาติทั่วโลก, จำค่าที่เลือกไว้
export const LANGS = [
  { code:'th', flag:'🇹🇭', name:'ไทย' },
  { code:'en', flag:'🇬🇧', name:'English' },
  { code:'zh', flag:'🇨🇳', name:'中文' },
  { code:'ja', flag:'🇯🇵', name:'日本語' },
  { code:'ko', flag:'🇰🇷', name:'한국어' },
  { code:'vi', flag:'🇻🇳', name:'Tiếng Việt' },
  { code:'lo', flag:'🇱🇦', name:'ລາວ' },
  { code:'km', flag:'🇰🇭', name:'ខ្មែរ' },
  { code:'my', flag:'🇲🇲', name:'မြန်မာ' },
  { code:'ms', flag:'🇲🇾', name:'Bahasa Melayu' },
  { code:'id', flag:'🇮🇩', name:'Bahasa Indonesia' },
  { code:'hi', flag:'🇮🇳', name:'हिन्दी' },
  { code:'ar', flag:'🇸🇦', name:'العربية' },
  { code:'es', flag:'🇪🇸', name:'Español' },
  { code:'fr', flag:'🇫🇷', name:'Français' },
  { code:'de', flag:'🇩🇪', name:'Deutsch' },
  { code:'pt', flag:'🇧🇷', name:'Português' },
];

type Dict = Record<string, string>;
const STR: Record<string, Dict> = {
th: { tagline:'ระบบบริหารเครือข่ายตัวแทน • ต้นไม้ฐาน 5 คน', nav_home:'หน้าแรก', nav_vision:'วิสัยทัศน์อิสรภาพทางการเงิน', nav_verify:'ตรวจสมาชิก', nav_prospects:'สมาชิกทั่วไป', nav_income:'รายได้', nav_notif:'แจ้งเตือน', nav_inquire:'สอบถามรายละเอียด', nav_1x5:'ระบบ 1 แตก 5 อัตโนมัติ', nav_n8n:'N8N Automation', n8n_editor:'แก้ไขเวิร์กโฟลว์', n8n_webhooks:'เว็บฮุค URL', n8n_workflows:'ดูเวิร์กโฟลว์', n8n_automation:'N8N Automation', n8n_status_running:'สถานะ: รันทำงาน', settings:'ตั้งค่า', logout:'ออกจากระบบ', login:'เข้าสู่ระบบ', register_interest:'สมัครแสดงความสนใจ', chat_title:'คุยกับ AI', chat_sub:'ระบบค้นหาด้วย AI อัจฉริยะ — พิมพ์ วางข้อมูล แนบไฟล์ แล้วให้ AI ช่วยทำงาน', menu_main:'เมนูหลัก', menu_admin:'ผู้ดูแลระบบ', menu_general:'สมาชิกทั่วไป', menu_agent:'ตัวแทน', menu_unit:'หัวหน้าหน่วยขึ้นไป', menu_center:'ผู้จัดการศูนย์ขึ้นไป', menu_region:'ผู้จัดการภาค (สูงสุด)', menu_system:'ระบบอัตโนมัติ', sb_admin:'ผู้ดูแลระบบ (Admin Dashboard)', sb_admin_messages:'ข้อความระบบ', sb_admin_reports:'รายงานผู้ดูแล', sb_admin_support:'ช่วยเหลือ/ร้องเรียน', sb_admin_consent:'ความยินยอม (PDPA)', sb_admin_backup:'สำรองข้อมูล', sb_os:'ระบบค้นหา (OS)', sb_rank_plans:'แผนตำแหน่ง', sb_income:'รายได้และเอกสาร', sb_appointments:'นัดหมาย', sb_chat:'คุยกับ AI', sb_recruit:'รับสมัคร/คัดเลือกตัวแทน', sb_n8n_editor:'n8n · สร้าง Workflow', sb_admin_menu:'เมนู Admin', sb_financial_freedom:'อิสรภาพทางการเงิน', sb_dashboard:'ภาพรวม', sb_members_prospects:'สมาชิกและผู้สนใจ', sb_tree:'ผังทีม 1:5', sb_receipts:'หลักฐานและผลงาน', sb_receipt_settings:'ตั้งค่าใบเสร็จ', sb_progress:'ความก้าวหน้า', sb_career:'ขึ้นตำแหน่ง', sb_periods:'ปิดยอดรายเดือน', sb_criteria:'เกณฑ์มาตรฐาน', sb_commissions:'ค่าคอมมิชชั่น', sb_reports:'รายงาน', sb_network:'สร้างเครือข่าย', sb_network_example:'ตัวอย่างเครือข่าย', sb_invite:'ชวนสมาชิก', sb_scan:'สแกนใบเสร็จ', sb_promotions:'ผู้ขึ้นตำแหน่ง', sb_my_members:'สมาชิกของฉัน', sb_documents:'สแกนใบเสร็จรับเงิน เข้าระบบ', sb_settings:'ตั้งค่า', sb_1x5_rules:'หลักเกณฑ์ 1 แตก 5' },
en: { tagline:'Agent network management • 5-wide tree', nav_home:'Home', nav_vision:'Financial Freedom Vision', nav_verify:'Verify members', nav_prospects:'General members', nav_income:'Income', nav_notif:'Notifications', nav_inquire:'Inquire', nav_1x5:'1×5 Network Autopilot', nav_n8n:'N8N Automation', n8n_editor:'Edit Workflow', n8n_webhooks:'Webhook URLs', n8n_workflows:'View Workflows', n8n_automation:'N8N Automation', n8n_status_running:'Status: Running', settings:'Settings', logout:'Log out', login:'Log in', register_interest:'Join as member', chat_title:'Chat with AI', chat_sub:'Smart AI search — type, paste, attach files and let AI help', menu_main:'Main menu', sb_financial_freedom:'Financial Freedom', sb_dashboard:'Overview', sb_members_prospects:'Members & prospects', sb_tree:'1:5 team tree', sb_receipts:'Receipts & performance', sb_receipt_settings:'Receipt settings', sb_progress:'Progress', sb_career:'Promotion', sb_periods:'Monthly close', sb_criteria:'Standards', sb_commissions:'Commissions', sb_reports:'Reports', sb_network:'Build network', sb_network_example:'Network example', sb_invite:'Invite members', sb_scan:'Scan receipt', sb_promotions:'Promotions', sb_my_members:'My members', sb_documents:'Financial documents', sb_settings:'Settings', sb_1x5_rules:'1:5 build rules' },
zh: { tagline:'代理网络管理 • 五宽树', nav_home:'首页', nav_vision:'财务自由愿景', nav_verify:'验证成员', nav_prospects:'一般会员', nav_income:'收入', nav_notif:'通知', nav_inquire:'询问详情', nav_n8n:'N8N 自动化', n8n_editor:'编辑工作流', n8n_webhooks:' webhook URL', n8n_workflows:'查看工作流', n8n_automation:'N8N 自动化', n8n_status_running:'状态：运行中', settings:'设置', logout:'退出', login:'登录', register_interest:'注册加入', chat_title:'与 AI 聊天', chat_sub:'智能 AI 搜索 — 输入、粘贴、上传文件，让 AI 帮忙', menu_main:'主菜单', sb_financial_freedom:'财务自由', sb_dashboard:'总览', sb_members_prospects:'成员与意向客户', sb_tree:'1:5 团队树', sb_receipts:'收据与业绩', sb_receipt_settings:'收据设置', sb_progress:'进展', sb_career:'晋升', sb_periods:'月结', sb_criteria:'标准', sb_commissions:'佣金表', sb_reports:'报表', sb_network:'发展网络', sb_network_example:'网络示例', sb_invite:'邀请成员', sb_scan:'扫描收据', sb_promotions:'晋升榜', sb_my_members:'我的成员', sb_documents:'财务文件', sb_settings:'设置', sb_1x5_rules:'1 裂 5 规则' },
ja: { tagline:'代理店ネットワーク管理 • 5ワイドツリー', nav_home:'ホーム', nav_vision:'財務的自由のビジョン', nav_verify:'メンバー確認', nav_prospects:'一般会員', nav_income:'収入', nav_notif:'通知', nav_inquire:'詳細問い合わせ', nav_n8n:'N8N オートメーション', n8n_editor:'ワークフロー編集', n8n_webhooks:'ウェブhook URL', n8n_workflows:'ワークフロー表示', n8n_automation:'N8N オートメーション', n8n_status_running:'ステータス：稼働中', settings:'設定', logout:'ログアウト', login:'ログイン', register_interest:'登録する', chat_title:'AI とチャット', chat_sub:'スマート AI 検索 — 入力・貼り付け・添付で AI が支援', menu_main:'メインメニュー', sb_financial_freedom:'経済的自立', sb_dashboard:'概要', sb_members_prospects:'メンバーと見込み客', sb_tree:'1:5 チームツリー', sb_receipts:'領収書と実績', sb_receipt_settings:'領収書設定', sb_progress:'進捗', sb_career:'昇進', sb_periods:'月次締め', sb_criteria:'基準', sb_commissions:'手数料表', sb_reports:'レポート', sb_network:'ネットワーク構築', sb_network_example:'ネットワーク例', sb_invite:'メンバー招待', sb_scan:'領収書スキャン', sb_promotions:'昇進者', sb_my_members:'私のメンバー', sb_documents:'財務書類', sb_settings:'設定', sb_1x5_rules:'1 分割 5 ルール' },
ko: { tagline:'대리점 네트워크 관리 • 5와이드 트리', nav_home:'홈', nav_vision:'재정적 자유 비전', nav_verify:'회원 확인', nav_prospects:'일반 회원', nav_income:'수입', nav_notif:'알림', nav_inquire:'문의', nav_n8n:'N8N 자동화', n8n_editor:'워크플로우 편집', n8n_webhooks:'웹훅 URL', n8n_workflows:'워크플로우 보기', n8n_automation:'N8N 자동화', n8n_status_running:'상태: 실행 중', settings:'설정', logout:'로그아웃', login:'로그인', register_interest:'회원 가입', chat_title:'AI와 채팅', chat_sub:'스마트 AI 검색 — 입력·붙여넣기·파일 첨부로 AI 도움', menu_main:'주 메뉴', sb_financial_freedom:'재정적 자유', sb_dashboard:'개요', sb_members_prospects:'회원 및 가망고객', sb_tree:'1:5 팀 트리', sb_receipts:'영수증과 실적', sb_receipt_settings:'영수증 설정', sb_progress:'진행 상황', sb_career:'승진', sb_periods:'월 마감', sb_criteria:'기준', sb_commissions:'수수료표', sb_reports:'보고서', sb_network:'네트워크 구축', sb_network_example:'네트워크 예시', sb_invite:'회원 초대', sb_scan:'영수증 스캔', sb_promotions:'승진자', sb_my_members:'내 회원', sb_documents:'재무 문서', sb_settings:'설정', sb_1x5_rules:'1 분할 5 규칙' },
vi: { tagline:'Quản lý mạng lưới đại lý • cây 5 nhánh', nav_home:'Trang chủ', nav_vision:'Tầm nhìn tự do tài chính', nav_verify:'Xác minh thành viên', nav_prospects:'Thành viên chung', nav_income:'Thu nhập', nav_notif:'Thông báo', nav_inquire:'Hỏi chi tiết', nav_n8n:'Tự động hóa N8N', n8n_editor:'Chỉnh sửa công việc', n8n_webhooks:'URL webhook', n8n_workflows:'Xem công việc', n8n_automation:'Tự động hóa N8N', n8n_status_running:'Trạng thái: Đang chạy', settings:'Cài đặt', logout:'Đăng xuất', login:'Đăng nhập', register_interest:'Đăng ký tham gia', chat_title:'Trò chuyện với AI', chat_sub:'Tìm kiếm AI thông minh — nhập, dán, đính kèm file để AI hỗ trợ', menu_main:'Menu chính', sb_financial_freedom:'Tự do tài chính', sb_dashboard:'Tổng quan', sb_members_prospects:'Thành viên & tiềm năng', sb_tree:'Cây đội 1:5', sb_receipts:'Biên lai & hiệu suất', sb_receipt_settings:'Cài đặt biên lai', sb_progress:'Tiến độ', sb_career:'Thăng chức', sb_periods:'Chốt tháng', sb_criteria:'Tiêu chuẩn', sb_commissions:'Bảng hoa hồng', sb_reports:'Báo cáo', sb_network:'Xây mạng lưới', sb_network_example:'Ví dụ mạng lưới', sb_invite:'Mời thành viên', sb_scan:'Quét biên lai', sb_promotions:'Thăng chức', sb_my_members:'Thành viên của tôi', sb_documents:'Tài liệu tài chính', sb_settings:'Cài đặt', sb_1x5_rules:'Quy tắc 1 phân 5' },
lo: { tagline:'ຄຸ້ມຄອງເຄືອຂ່າຍຕົວແທນ • ຕົ້ນໄມ້ 5 ກິ່ງ', nav_home:'ໜ້າຫຼັກ', nav_vision:'ເຫດວົງເງິນອິດສາທານ', nav_verify:'ກວດສອບສະມາຊິກ', nav_prospects:'ສະມາຊິກທົ່ວໄປ', nav_income:'ລາຍໄດ້', nav_notif:'ແຈ້ງເຕືອນ', nav_inquire:'ສອກລາຍລະອຽດ', settings:'ຕັ້ງຄ່າ', logout:'ອອກຈາກລະບົບ', login:'ເຂົ້າສູ່ລະບົບ', register_interest:'ສະໝັກເຂົ້າຮ່ວມ', chat_title:'ສົນທະນາກັບ AI', chat_sub:'ຄົ້ນຫາອັດສະລິຍະ — ພິມ ວາງ ແນບໄຟລ໌ ໃຫ້ AI ຊ່ວຍ', menu_main:'ເມນູຫຼັກ', sb_financial_freedom:'ອິດສະລະພາບທາງດ້ານການເງິນ', sb_dashboard:'ພາບລວມ', sb_members_prospects:'ສະມາຊິກແລະຜູ້ສົນໃຈ', sb_tree:'ຜັງທີມ 1:5', sb_receipts:'ໃບຮັບເງິນແລະຜົນງານ', sb_receipt_settings:'ຕັ້ງຄ່າໃບຮັບເງິນ', sb_progress:'ຄວາມຄືບໜ້າ', sb_career:'ເລື່ອນຕຳແໜ່ງ', sb_periods:'ປິດຍອດລາຍເດືອນ', sb_criteria:'ມາດຕະຖານ', sb_commissions:'ຕາຕະລາງຄ່ານາຍໜ້າ', sb_reports:'ລາຍງານ', sb_network:'ສ້າງເຄືອຂ່າຍ', sb_network_example:'ຕົວຢ່າງເຄືອຂ່າຍ', sb_invite:'ເຊີນສະມາຊິກ', sb_scan:'ສະແກນໃບຮັບເງິນ', sb_promotions:'ຜູ້ເລື່ອນຕຳແໜ່ງ', sb_my_members:'ສະມາຊິກຂອງຂ້ອຍ', sb_documents:'ເອກະສານການເງິນ', sb_settings:'ຕັ້ງຄ່າ' },
km: { tagline:'គ្រប់គ្រងបណ្តាញភ្នាក់ងារ • មែកធាង 5', nav_home:'ទំព័រដើម', nav_vision:'ការមើលឃើញឯករាជ្យផ្នែកហិរញ្ញវត្ថុ', nav_verify:'ផ្ទៀងផ្ទាត់សមាជិក', nav_prospects:'សមាជិកទូទៅ', nav_income:'ចំណូល', nav_notif:'ការជូនដំណឹង', nav_inquire:'សួរលម្អិត', settings:'ការកំណត់', logout:'ចាកចេញ', login:'ចូលប្រព័ន្ធ', register_interest:'ចុះឈ្មោះចូលរួម', chat_title:'ជជែកជាមួយ AI', chat_sub:'ស្វែងរក AI ឆ្លាត — វាយ បិទភ្ជាប់ ភ្ជាប់ឯកសារ', menu_main:'ម៉ឺនុយមេ', sb_financial_freedom:'សេរីភាពហិរញ្ញវត្ថុ', sb_dashboard:'ទិដ្ឋភាពទូទៅ', sb_members_prospects:'សមាជិកនិងអ្នកចាប់អារម្មណ៍', sb_tree:'មែកធាងក្រុម 1:5', sb_receipts:'បង្កាន់ដៃនិងស្នាដៃ', sb_receipt_settings:'ការកំណត់បង្កាន់ដៃ', sb_progress:'វឌ្ឍនភាព', sb_career:'តម្លើងតំណែង', sb_periods:'បិទยอดប្រចាំខែ', sb_criteria:'ស្តង់ដារ', sb_commissions:'តារាងកម្រៃជើងសា', sb_reports:'របាយការណ៍', sb_network:'កសាងបណ្តាញ', sb_network_example:'ឧទាហរណ៍បណ្តាញ', sb_invite:'អញ្ជើញសមាជិក', sb_scan:'ស្កេនបង្កាន់ដៃ', sb_promotions:'អ្នកតម្លើងតំណែង', sb_my_members:'សមាជិករបស់ខ្ញុំ', sb_documents:'ឯកសារហិរញ្ញវត្ថុ', sb_settings:'ការកំណត់' },
my: { tagline:'ကိုယ်စားလှယ်ကွန်ရက်စီမံခန့်ခွဲမှု • အခက် ၅', nav_home:'ပင်မစာမျက်နှာ', nav_vision:'ငွေကြေးထူးချဲ့အာရုံကြောင်းသဘောထား', nav_verify:'အဖွဲ့ဝင်စစ်ဆေးရန်', nav_prospects:'အထွေထွေအဖွဲ့ဝင်', nav_income:'ဝင်ငွေ', nav_notif:'အသိပေးချက်များ', nav_inquire:'သတင်းအချက်အလက်မေးမြန်းရန်', settings:'ဆက်တင်များ', logout:'ထွက်ရန်', login:'ဝင်ရန်', register_interest:'ပါဝင်ရန် စာရင်းသွင်းရန်', chat_title:'AI နှင့်စကားပြောရန်', chat_sub:'စမတ် AI ရှာဖွေမှု — ရိုက်ထည့် ကူးထည့် ဖိုင်တွဲရန်', menu_main:'ပင်မမီနူး', sb_financial_freedom:'ငွေကြေးလွတ်လပ်မှု', sb_dashboard:'ခြုံငုံသုံးသပ်ချက်', sb_members_prospects:'အဖွဲ့ဝင်များနှင့် စိတ်ဝင်စားသူများ', sb_tree:'အသင်း 1:5', sb_receipts:'ပြေစာနှင့် စွမ်းဆောင်ရည်', sb_receipt_settings:'ပြေစာဆက်တင်များ', sb_progress:'တိုးတက်မှု', sb_career:'ရာထူးတိုးရန်', sb_periods:'လချုပ်', sb_criteria:'စံချိန်စံညွှန်းများ', sb_commissions:'ကော်မရှင်ဇယား', sb_reports:'အစီရင်ခံစာများ', sb_network:'ကွန်ရက်တည်ဆောက်ရန်', sb_network_example:'ကွန်ရက်နမူနာ', sb_invite:'အဖွဲ့ဝင်ဖိတ်ရန်', sb_scan:'ပြေစာစကင်ဖတ်ရန်', sb_promotions:'ရာထူးတိုးသူများ', sb_my_members:'ကျွန်ုပ်၏အဖွဲ့ဝင်များ', sb_documents:'ဘဏ္ဍာရေးစာရွက်စာတမ်းများ', sb_settings:'ဆက်တင်များ' },
ms: { tagline:'Pengurusan rangkaian ejen • pokok 5 dahan', nav_home:'Laman utama', nav_vision:'Visi Kebebasan Kewangan', nav_verify:'Sahkan ahli', nav_prospects:'Ahli umum', nav_income:'Pendapatan', nav_notif:'Pemberitahuan', nav_inquire:'Tanyakan rincian', settings:'Tetapan', logout:'Log keluar', login:'Log masuk', register_interest:'Daftar sertai', chat_title:'Berbual dengan AI', chat_sub:'Carian AI pintar — taip, tampal, lampir fail', menu_main:'Menu utama', sb_financial_freedom:'Kebebasan Kewangan', sb_dashboard:'Gambaran', sb_members_prospects:'Ahli & prospek', sb_tree:'Pokok pasukan 1:5', sb_receipts:'Resit & prestasi', sb_receipt_settings:'Tetapan resit', sb_progress:'Kemajuan', sb_career:'Kenaikan pangkat', sb_periods:'Tutup bulanan', sb_criteria:'Standard', sb_commissions:'Jadual komisen', sb_reports:'Laporan', sb_network:'Bina rangkaian', sb_network_example:'Contoh rangkaian', sb_invite:'Jemput ahli', sb_scan:'Imbas resit', sb_promotions:'Kenaikan pangkat', sb_my_members:'Ahli saya', sb_documents:'Dokumen kewangan', sb_settings:'Tetapan' },
id: { tagline:'Manajemen jaringan agen • pohon 5 cabang', nav_home:'Beranda', nav_vision:'Visi Kebebasan Finansial', nav_verify:'Verifikasi anggota', nav_prospects:'Anggota umum', nav_income:'Pendapatan', nav_notif:'Notifikasi', nav_inquire:'Tanyakan detail', settings:'Pengaturan', logout:'Keluar', login:'Masuk', register_interest:'Daftar bergabung', chat_title:'Ngobrol dengan AI', chat_sub:'Pencarian AI pintar — ketik, tempel, lampirkan file', menu_main:'Menu utama', sb_financial_freedom:'Kebebasan Finansial', sb_dashboard:'Ringkasan', sb_members_prospects:'Anggota & prospek', sb_tree:'Pohon tim 1:5', sb_receipts:'Kwitansi & kinerja', sb_receipt_settings:'Pengaturan kwitansi', sb_progress:'Kemajuan', sb_career:'Promosi', sb_periods:'Tutup bulanan', sb_criteria:'Standar', sb_commissions:'Tabel komisi', sb_reports:'Laporan', sb_network:'Bangun jaringan', sb_network_example:'Contoh jaringan', sb_invite:'Undang anggota', sb_scan:'Pindai kwitansi', sb_promotions:'Promosi', sb_my_members:'Anggotaku', sb_documents:'Dokumen keuangan', sb_settings:'Pengaturan' },
hi: { tagline:'एजेंट नेटवर्क प्रबंधन • 5-शाखा वृक्ष', nav_home:'मुख्य पृष्ठ', nav_vision:'वित्तीय स्वतंत्रता दृष्टि', nav_verify:'सदस्य सत्यापित करें', nav_prospects:'सामान्य सदस्य', nav_income:'आय', nav_notif:'सूचनाएं', nav_inquire:'विवरण पूछें', settings:'सेटिंग', logout:'लॉग आउट', login:'लॉग इन', register_interest:'शामिल हों', chat_title:'AI से चैट करें', chat_sub:'स्मार्ट AI खोज — लिखें, पेस्ट करें, फाइल जोड़ें', menu_main:'मुख्य मेनू', sb_financial_freedom:'वित्तीय स्वतंत्रता', sb_dashboard:'अवलोकन', sb_members_prospects:'सदस्य और संभावित ग्राहक', sb_tree:'1:5 टीम वृक्ष', sb_receipts:'रसीद व प्रदर्शन', sb_receipt_settings:'रसीद सेटिंग', sb_progress:'प्रगति', sb_career:'पदोन्नति', sb_periods:'मासिक समापन', sb_criteria:'मानक', sb_commissions:'कमीशन तालिका', sb_reports:'रिपोर्ट', sb_network:'नेटवर्क बनाएं', sb_network_example:'नेटवर्क उदाहरण', sb_invite:'सदस्य आमंत्रित करें', sb_scan:'रसीद स्कैन करें', sb_promotions:'पदोन्नति', sb_my_members:'मेरे सदस्य', sb_documents:'वित्तीय दस्तावेज़', sb_settings:'सेटिंग' },
ar: { tagline:'إدارة شبكة الوكلاء • شجرة خماسية', nav_home:'الرئيسية', nav_vision:'رؤية الحرية المالية', nav_verify:'التحقق من الأعضاء', nav_prospects:'الأعضاء العامون', nav_income:'الدخل', nav_notif:'الإشعارات', nav_inquire:'استفسار التفاصيل', settings:'الإعدادات', logout:'تسجيل الخروج', login:'تسجيل الدخول', register_interest:'انضم إلينا', chat_title:'تحدث مع الذكاء الاصطناعي', chat_sub:'بحث ذكي — اكتب والصق وأرفق الملفات', menu_main:'القائمة الرئيسية', sb_financial_freedom:'الحرية المالية', sb_dashboard:'نظرة عامة', sb_members_prospects:'الأعضاء والمهتمون', sb_tree:'شجرة الفريق 1:5', sb_receipts:'الإيصالات والأداء', sb_receipt_settings:'إعدادات الإيصالات', sb_progress:'التقدم', sb_career:'الترقية', sb_periods:'الإغلاق الشهري', sb_criteria:'المعايير', sb_commissions:'جدول العمولات', sb_reports:'التقارير', sb_network:'بناء الشبكة', sb_network_example:'مثال الشبكة', sb_invite:'دعوة الأعضاء', sb_scan:'مسح الإيصال', sb_promotions:'الترقيات', sb_my_members:'أعضائي', sb_documents:'المستندات المالية', sb_settings:'الإعدادات' },
es: { tagline:'Gestión de red de agentes • árbol de 5', nav_home:'Inicio', nav_vision:'Visión de Libertad Financiera', nav_verify:'Verificar miembros', nav_prospects:'Miembros generales', nav_income:'Ingresos', nav_notif:'Notificaciones', nav_inquire:'Consultar detalles', settings:'Ajustes', logout:'Salir', login:'Entrar', register_interest:'Unirse', chat_title:'Chatear con IA', chat_sub:'Búsqueda IA inteligente — escribe, pega y adjunta archivos', menu_main:'Menú principal', sb_financial_freedom:'Libertad financiera', sb_dashboard:'Resumen', sb_members_prospects:'Miembros y prospectos', sb_tree:'Árbol 1:5', sb_receipts:'Recibos y desempeño', sb_receipt_settings:'Ajustes de recibos', sb_progress:'Progreso', sb_career:'Ascenso', sb_periods:'Cierre mensual', sb_criteria:'Estándares', sb_commissions:'Tabla de comisiones', sb_reports:'Informes', sb_network:'Construir red', sb_network_example:'Ejemplo de red', sb_invite:'Invitar miembros', sb_scan:'Escanear recibo', sb_promotions:'Ascensos', sb_my_members:'Mis miembros', sb_documents:'Documentos financieros', sb_settings:'Ajustes' },
fr: { tagline:'Gestion du réseau d’agents • arbre à 5 branches', nav_home:'Accueil', nav_vision:'Vision de la Liberté Financière', nav_verify:'Vérifier les membres', nav_prospects:'Membres généraux', nav_income:'Revenus', nav_notif:'Notifications', nav_inquire:'Demander des détails', settings:'Paramètres', logout:'Déconnexion', login:'Connexion', register_interest:'Rejoindre', chat_title:'Discuter avec l’IA', chat_sub:'Recherche IA intelligente — écrivez, collez, joignez des fichiers', menu_main:'Menu principal', sb_financial_freedom:'Liberté financière', sb_dashboard:'Aperçu', sb_members_prospects:'Membres et prospects', sb_tree:'Arbre d’équipe 1:5', sb_receipts:'Reçus et performance', sb_receipt_settings:'Paramètres des reçus', sb_progress:'Progrès', sb_career:'Promotion', sb_periods:'Clôture mensuelle', sb_criteria:'Normes', sb_commissions:'Tableau des commissions', sb_reports:'Rapports', sb_network:'Construire le réseau', sb_network_example:'Exemple de réseau', sb_invite:'Inviter des membres', sb_scan:'Scanner un reçu', sb_promotions:'Promotions', sb_my_members:'Mes membres', sb_documents:'Documents financiers', sb_settings:'Paramètres' },
de: { tagline:'Agentennetzwerk-Verwaltung • 5er-Baum', nav_home:'Start', nav_vision:'Vision von Finanzieller Freiheit', nav_verify:'Mitglieder prüfen', nav_prospects:'Allgemeine Mitglieder', nav_income:'Einkommen', nav_notif:'Mitteilungen', nav_inquire:'Details anfragen', settings:'Einstellungen', logout:'Abmelden', login:'Anmelden', register_interest:'Beitreten', chat_title:'Mit KI chatten', chat_sub:'Intelligente KI-Suche — tippen, einfügen, Dateien anhängen', menu_main:'Hauptmenü', sb_financial_freedom:'Finanzielle Freiheit', sb_dashboard:'Überblick', sb_members_prospects:'Mitglieder & Interessenten', sb_tree:'1:5-Teambaum', sb_receipts:'Belege & Leistung', sb_receipt_settings:'Beleg-Einstellungen', sb_progress:'Fortschritt', sb_career:'Beförderung', sb_periods:'Monatsabschluss', sb_criteria:'Standards', sb_commissions:'Provisionstabelle', sb_reports:'Berichte', sb_network:'Netzwerk aufbauen', sb_network_example:'Netzwerkbeispiel', sb_invite:'Mitglieder einladen', sb_scan:'Beleg scannen', sb_promotions:'Beförderungen', sb_my_members:'Meine Mitglieder', sb_documents:'Finanzdokumente', sb_settings:'Einstellungen' },
pt: { tagline:'Gestão da rede de agentes • árvore de 5', nav_home:'Início', nav_vision:'Visão de Liberdade Financeira', nav_verify:'Verificar membros', nav_prospects:'Membros gerais', nav_income:'Renda', nav_notif:'Notificações', nav_inquire:'Solicitar detalhes', settings:'Configurações', logout:'Sair', login:'Entrar', register_interest:'Participar', chat_title:'Conversar com IA', chat_sub:'Busca IA inteligente — digite, cole e anexe arquivos', menu_main:'Menu principal', sb_financial_freedom:'Liberdade financeira', sb_dashboard:'Visão geral', sb_members_prospects:'Membros e prospectos', sb_tree:'Árvore 1:5', sb_receipts:'Recibos e desempenho', sb_receipt_settings:'Configurações de recibos', sb_progress:'Progresso', sb_career:'Promoção', sb_periods:'Fechamento mensal', sb_criteria:'Padrões', sb_commissions:'Tabela de comissões', sb_reports:'Relatórios', sb_network:'Construir rede', sb_network_example:'Exemplo de rede', sb_invite:'Convidar membros', sb_scan:'Escanear recibo', sb_promotions:'Promoções', sb_my_members:'Meus membros', sb_documents:'Documentos financeiros', sb_settings:'Configurações' },
};

export function getLang(): string {
  if(typeof window === 'undefined') return 'th';
  const v = localStorage.getItem('app-lang') || 'th';
  return STR[v] ? v : 'th';
}
export function setLang(code: string){
  if(typeof window === 'undefined') return;
  localStorage.setItem('app-lang', code);
  window.dispatchEvent(new CustomEvent('app-lang-change', { detail: code }));
}
export function t(key: string, lang?: string): string {
  const l = lang || getLang();
  return STR[l]?.[key] || STR.th[key] || key;
}
export function useT(){
  const [lang, setL] = useState(getLang());
  useEffect(()=>{
    const h = (e:any)=> setL(e.detail || getLang());
    window.addEventListener('app-lang-change', h);
    return ()=> window.removeEventListener('app-lang-change', h);
  },[]);
  return { lang, t: (key:string)=> t(key, lang) };
}
