// ใช้ Supabase JS Client ในโปรเจกต์นี้โดยตรง — สร้างตารางทั้งหมด
import { createClient } from '@supabase/supabase-js';

const supabase = createClient('https://ytcuepcwxpogqmlntjks.supabase.co', 'sb_publishable_Dil4q88IBcTGuEIOVCe09A_mA_c496W');

async function createAllTables() {
  console.log('🚀 เริ่มสร้างตาราง...');

  // สร้างตาราง provinces
  const { error: e1 } = await supabase.rpc('create_table', {
    name: 'provinces',
    definition: 'id INT PRIMARY KEY, name_th TEXT, name_en TEXT, geography_id INT, created_at TIMESTAMPTZ, updated_at TIMESTAMPTZ, deleted_at TIMESTAMPTZ'
  });
  if (e1) console.log('✗ provinces:', e1.message);
  else console.log('✓ provinces สร้างสำเร็จ');

  // สร้างตาราง districts
  const { error: e2 } = await supabase.rpc('create_table', {
    name: 'districts',
    definition: 'id INT PRIMARY KEY, name_th TEXT, name_en TEXT, province_id INT, created_at TIMESTAMPTZ, updated_at TIMESTAMPTZ, deleted_at TIMESTAMPTZ'
  });
  if (e2) console.log('✗ districts:', e2.message);
  else console.log('✓ districts สร้างสำเร็จ');

  // สร้างตาราง sub_districts
  const { error: e3 } = await supabase.rpc('create_table', {
    name: 'sub_districts',
    definition: 'id INT PRIMARY KEY, zip_code INT, name_th TEXT, name_en TEXT, district_id INT, lat FLOAT, long FLOAT, created_at TIMESTAMPTZ, updated_at TIMESTAMPTZ, deleted_at TIMESTAMPTZ'
  });
  if (e3) console.log('✗ sub_districts:', e3.message);
  else console.log('✓ sub_districts สร้างสำเร็จ');

  // สร้างตาราง commissions
  const { error: e4 } = await supabase.rpc('create_table', {
    name: 'commissions',
    definition: 'id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version TEXT, effective_from DATE, effective_to DATE, source_ref TEXT, products JSONB, created_at TIMESTAMPTZ DEFAULT NOW()'
  });
  if (e4) console.log('✗ commissions:', e4.message);
  else console.log('✓ commissions สร้างสำเร็จ');

  console.log('\n✅ สร้างตารางเสร็จสิ้น!');
}

createAllTables().catch(console.error);
